### ISSUE TITLE
Please remove the jupyter dependency because it was last updated in 2015 and doesn't reflect the current state of Jupyter packages

### ISSUE THREAD

**Issue by yurivict** [HofstadterTools/HofstadterTools#17]
[Jupyter package](https://pypi.org/project/jupyter/) on the PYPI website.

**Comment by bartandrews** [comment]
Thank you for spotting this! Do you know the name of the new package that replaces this? Is it `pip install notebook` ?

**Comment by bartandrews** [comment]
I have now checked this in a venv. Even though the `jupyter` package PyPI release date is old, `pip install jupyter` will install the latest version of all jupyter-related packages, i.e. everything from `pip install notebook`, and a little bit more.

**Comment by bartandrews** [comment]
After closer inspection, `jupyter` is a metapackage that automatically installs all of the latest jupyter components in one go. It is still part of Project Jupyter (https://pypi.org/org/jupyter/) and is not deprecated, as far as I can tell. Therefore, I am closing this issue now.
